language: go
go:
 - 1.8
 - 1.11
 - 1.12
 - tip

matrix:
  allow_failures:
  - go: tip

install:
 - if [[ $TRAVIS_GO_VERSION == 1.12* ]]; then go get github.com/mattn/goveralls; fi

script:
 - make test
 # only run test-coverage for one go version
 - if [[ $TRAVIS_GO_VERSION == 1.12* ]]; then make test-coverage; $HOME/gopath/bin/goveralls -coverprofile=magnacarto.coverprofile -service=travis-ci; fi
